version: "3.7"
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile
    environment:
      MYSQL_USER: docker-database
      MYSQL_PASSWORD: docker-database-pwd
      MYSQL_DATABASE: api_smtp-dev
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: db:3306
    ports:
      - "8080:8080"
    volumes:
      - ./:/go:rw
    networks:
      - backend
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: docker-database
      MYSQL_PASSWORD: docker-database-pwd
      MYSQL_DATABASE: api_smtp-dev
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db_data1:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data1: {}

networks:
  backend:
    driver: "bridge"