version: "3.7"
services:
  web:
    restart: always
    image: go-app
    ports:
      - 8080:8080
    environment:
      MYSQL_USER: docker-database
      MYSQL_PASSWORD: docker-database-pwd
      MYSQL_DATABASE: api_smtp-dev
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: db:3306

    links:
      -  db
    networks:
      - backend
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: docker-database
      MYSQL_PASSWORD: docker-database-pwd
      MYSQL_DATABASE: api_smtp-dev
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db_data1:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data1: {}

networks:
  backend:
    driver: "bridge"